<?php $article = $this->article;?>
<div class="article">
    <a href="<?= $this->url(array('id' => $article->getArticleId()), 'articleDelete', TRUE, FALSE);?>" >Supprimer l'article</a><br />
    <a href="<?= $this->url(array('id' => $article->getArticleId()), 'articleUpdate', TRUE, FALSE);?>" >Modification de l'article</a><br />
    <h2><?= $article->getArticleTitle()?></h2>
    <h3>Par <?= $article->getAuthor()->getAuthorName()?></h3>
    <div class="articleContent">
    <?= $article->getArticleContent()?>
    </div>
</div>